name: Build

on:
  push:
    tags:
      "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files:  build/libs/moreliver-*.jar
          draft: true
          fail_on_unmatched_files: true
